### ISSUE TITLE
Locking only a single language variant

### ISSUE THREAD

**Issue by richardhriech** [Rockerby/Umbraco.BackOfficeEditorView#5]
Hey there,

Great package, we already started using it in our project, it's working flawlessly.
A request came from the editors though, they would like to be able to use the locking/notification feature only for a single language variant under a node.
We are using several language variants for a node, so the overwriting issue only comes up when two editors for the same language try to edit the same page.
![image](https://github.com/Rockerby/Umbraco.BackOfficeEditorView/assets/71294989/0a3bd089-6eb9-4fca-b5d7-b3a875b692c7)

@Rockerby If you have no capacity to implement this feature, I would try it myself. Could give me pointers where to start?
Thank you!

**Comment by Rockerby** [comment]
Thanks @richardhriech , glad to hear you're finding the package useful!

I'm fairly busy at the moment and unlikely to find time to dev this; but happy to help support if you want to give it a go.

I think the crooks of this will lie in the [CacheContentLockManager](https://github.com/Rockerby/Umbraco.BackOfficeEditorView/blob/main/BackOfficeEditorView.Core/Services/CacheContentLockManager.cs), where you'll need to pass in certain variant settings for what you're after. You'll also need to update the back office elements so that it checks on variant change (not sure on that, but I'm sure there'll be a way!) And be sure to have this as a setting in the appSettings so people can turn on/off at their leisure.

A great starting point to understand how the current locking functionality works would be to check out the [PR](https://github.com/Rockerby/Umbraco.BackOfficeEditorView/pull/4/files) from @lssweatherhead which has everything in it.

@lssweatherhead did a cracking job of adding the lock feature in, so may be able to add to what I've said.

**Comment by richardhriech** [comment]
@Rockerby I wrote a bunch of code, but I have a hard time debugging it.
Unfortunately, the [Umbraco docs](https://docs.umbraco.com/umbraco-cms/v/12.latest/extending/packages/creating-a-package) doesn't mention testing a package's logic before creating a nuget.
Can you point me to some resource that will help me catch up? The only way I could test my code so far is that I included the BackOfficeEditorView projects in my Umbraco solution, but SingnalR can only receive and doesn't send content for some reason...

**Comment by Rockerby** [comment]
Great stuff @richardhriech, looking forward to seeing what's been done.

In order to test what you've done you need to spin up your own Umbraco instance, add the Core project as a reference and then manually copy the App_Plugins folder from the Assets project to the new Umbraco project. I have it in my list to help open this up to support local dev better so there's no manual copying involved!

To show you a working copy, you can see this PR https://github.com/Rockerby/Umbraco.BackOfficeEditorView/pull/6 - I'm not planning to merge this into main, purely made it to show you it working. Creds are admin@example.com / '1234567890' (including the quotes).

Any test site files shouldn't be committed into the branch, please.

**Comment by richardhriech** [comment]
Thank you so much @Rockerby , the example project helped a lot. A PR is coming very soon.

**Comment by Rockerby** [comment]
Great work there @richardhriech 👍 

I've merged in the PR and released v1.2.0 which has this.

Thanks for your contribution, #h5yr!
